### PR TITLE
feat(multicolors): add newer games color support

### LINKED ISSUE #2: Wrong color tag in Insurgency
image

### PR DESCRIPTION
**Pull request by maximee-leroyy**
Tested for more than a year on our servers (https://nide.gg) and works on both CS:S and CS:GO

- [x] CSS
- [x] CSGO
- [x] Insurgency
- [ ] L4D2
- [ ] TF2

### CODE REVIEW

**Comment by maximee-leroyy** [comment]
cc @Bara

**Review by Rushaway — APPROVED** [review]

**Comment by Bara** [comment]
I try to test this this week or weekend.

**Comment by maximee-leroyy** [comment]
> I try to test this this week or weekend.

Thank you a lot, we use it with this code if you are interested:
- https://github.com/srcdslab/sm-plugin-CustomChatColors

**Comment by Rushaway** [comment]
Any updates? 👍

**Comment by Bara** [comment]
Not yet, sorry.

But since you removed the `colors.inc` it would make more sense to replace the `multicolors.inc` with `morecolors.inc`. So we don't need to include the second include file anymore and it's All in one include file.

**Comment by maximee-leroyy** [comment]
> Not yet, sorry.
> 
> But since you removed the `colors.inc` it would make more sense to replace the `multicolors.inc` with `morecolors.inc`. So we don't need to include the second include file anymore and it's All in one include file.

good idea, i will do it soon then!

**Comment by Bara** [comment]
Ping me when you pushed the changes 👌🏻 I set it on my todo list

**Comment by maximee-leroyy** [comment]
done! @Bara

**Comment by Bara** [comment]
> done! @Bara


I'll test it when I'm feeling me better. 👍🏻 It's already on my todo list

**Comment by Bara** [comment]
In which case is it necessary to keep [CPrintToChat](https://github.com/Bara/Multi-Colors/blob/d908feddaababa450a75cb539134ce20e63a7804/addons/sourcemod/scripting/include/multicolors.inc#L1128-L1134)?

Couldn't we just delete it and renaming `MC_PrintToChat` to `CPrintToChat`? We [SetGlobalTransTarget and VFormat](https://github.com/Bara/Multi-Colors/blob/d908feddaababa450a75cb539134ce20e63a7804/addons/sourcemod/scripting/include/multicolors.inc#L71-L73) in `MC_PrintToChat` too. I think we can remove some C* functions for replacing it with the MC_* functions for reducing the amount of code.

**Comment by maximee-leroyy** [comment]
> In which case is it necessary to keep [CPrintToChat](https://github.com/Bara/Multi-Colors/blob/d908feddaababa450a75cb539134ce20e63a7804/addons/sourcemod/scripting/include/multicolors.inc#L1128-L1134)?
> 
> Couldn't we just delete it and renaming `MC_PrintToChat` to `CPrintToChat`? We [SetGlobalTransTarget and VFormat](https://github.com/Bara/Multi-Colors/blob/d908feddaababa450a75cb539134ce20e63a7804/addons/sourcemod/scripting/include/multicolors.inc#L71-L73) in `MC_PrintToChat` too. I think we can remove some C* functions for replacing it with the MC_* functions for reducing the amount of code.

okay i will try to do this soon then

**Comment by Bara** [comment]
Otherwise I would do this too while testing and I already installed/prepared few gameservers (CSGO, CSS, TF2, L4D2 and Insurgency) for testing multicolors.

**Comment by maximee-leroyy** [comment]
> Otherwise I would do this too while testing and I already installed/prepared few gameservers (CSGO, CSS, TF2, L4D2 and Insurgency) for testing multicolors.

Okay as you which so remove MC_* functions for only C* functions

**Comment by Bara** [comment]
In CSS, CSGO, Insurgency and TF2 it looks fine, except L4D2 seems to not work(?). Will take a look later.

**Comment by Bara** [comment]
@maxime1907 can you test this version too? if if works fine for you, I'll merge this.

**Comment by maximee-leroyy** [comment]
> @maxime1907 can you test this version too? if if works fine for you, I'll merge this.

okay gonna test it!

- [x] CSS
- [x] CSGO

**Comment by maximee-leroyy** [comment]
> > @maxime1907 can you test this version too? if if works fine for you, I'll merge this.
> 
> okay gonna test it!
> 
> * [x]  CSS
> * [x]  CSGO

works like a charm you can merge it 🙂 @Bara

**Comment by fbef0102** [comment]
I tested in l4d2
Does not work
#16

**Pull request merged**
